### ISSUE TITLE
Add python linter Black to github action

### ISSUE THREAD

**Issue by jwu910** [BobaTalks/internship-tracker#53]
Can probably benefit from some CI here. Backend linter for python?

Something like this _should_ work

https://docs.github.com/en/actions

```yaml
name: GitHub Actions Checks
run-name: Running Lint check on Pull Request from ${{ github.actor }} 🚀
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
        with:
          args: ". --check"

      - run: echo "🍏 This job's status is ${{ job.status }}."
```
